experimental_monorepo_root = true

[monorepo]
config_roots = [
  "apps/portfolio"
]

[tools]
# ==== TOOLS | DEVCONTAINER =========================================
node = "24.16.0"
devcontainer-cli = "0.87.0"

# ==== TOOLS | GITHUB ===============================================
act = "0.2.82"


# ==== ENVIRONMENTS =================================================
[env]

# ==== ENVIRONMENTS | MISE ==========================================
MISE_EXPERIMENTAL = "true"
MISE_LOG_LEVEL = "INFO"
MISE_PROJECT_NAME = "{{config_root | basename}}"


# ==== TASKS | AGENT ================================================

[tasks."agent:context:resume"]
description = "Create a single file that resume the current context of repository"
run = '''
#!/usr/bin/env bash

npx repomix --include '*.*,apps/portfolio/**/*.*'
'''
hide = true

# ==== TASKS | WORKSPACE =============================================

[tasks."workspace:up"]
description = "Create an isolate container where develop"
run = '''
#!/usr/bin/env bash

workspace up --workspace-folder . --id-label name='{{ env.MISE_PROJECT_NAME }}'
'''

[tasks."workspace:down"]
description = "Destroy the workspace"
run = '''
#!/usr/bin/env bash
CONTAINER_ID=$(docker ps -a -q --filter "label=name=${MISE_PROJECT_NAME}")

if [ -z "$CONTAINER_ID" ]; then
  exit 1
fi

docker rm -f "${CONTAINER_ID}"
'''

[tasks."workspace:exec"]
description = "Attach a bash session to the workspace"
usage = '''
 arg "<args>" help="Arguments to pass"
'''
run = '''
#!/usr/bin/env bash
workspace exec --workspace-folder . --id-label name='{{ env.MISE_PROJECT_NAME }}' {{ usage.args }}
'''

[tasks."workspace:shell"]
description = "Attach a bash session to the workspace"
run = '''
#!/usr/bin/env bash
workspace up --workspace-folder . --id-label name='{{ env.MISE_PROJECT_NAME }}'
workspace exec --workspace-folder . --id-label name='{{ env.MISE_PROJECT_NAME }}' bash
'''

# ==== TASKS | WORKFLOW =============================================

[tasks."workflow:run"]
description = "Run workflow files"
run = [
  "act pull_request"
]

#[tasks."dev"]
#description = "Avvia l'Inner Loop con Skaffold"
#run = "skaffold dev --port-forward"
