[tools]
skaffold = "latest"
k3d = "latest"
helm = "latest"
kubectl = "latest"

[env]
K8S_CLUSTER_NAME = 'dev'

[tasks."dev"]
description = "Avvia l'Inner Loop con Skaffold"
run = "skaffold dev --port-forward"
