[tools]
node = "24.16.0"
npm = "latest"

[tasks."setup"]
description = "Configure project"
run = [
  "npm install"
]

[tasks."build"]
description = "Build application"
run = "npm run next:build"

[tasks."dev"]
description = "Run application in development mode"
run = "npm run next:dev"

[tasks."start"]
description = "Run application in production mode"
run = "npm run next:start"

[tasks."storybook:dev"]
description = "Run storybook application"
run = "npm run storybook:dev"

[tasks."storybook:build"]
description = "Build storybook stories"
run = "npm run storybook:build"

[tasks."storybook:test"]
description = "Test storybook stories"
run = "npm run storybook:test"
