[tools]
node = "24.16.0"
npm = "latest"

[tasks."setup"]
description = "Configure project"
run = [
  "npm install"
]

[tasks."build"]
description = "Build application"
run = "npm run build"


[tasks."dev"]
description = "Run application in development mode"
run = "npm run dev"

[tasks."storybook"]
description = "Run storybook"
run = "npm run storybook"
